package main.java.com.infolob.container.resources;

public class Constants {

	public static final String ID_USERNAME = "usernameField";
	public static final String ID_PASSOWRD = "passwordField";
	public static final String ID_SUBMITLOGIN = "button[class='OraButton left']";
	public static final String CSS_LEFTMENU = "h1[class='x1f']";
	public static final String ID_LEFTMENU = "menuTable";
	public static final String ID_LEFTMENU_LAYOUT = "menuLayout_div";
	public static final String LT_ADVANCED_PLANNING_ADMINISTRATOR = "Advanced Planning Administrator";
	public static final String LT_APPLICATITON_DIGNOSTICS = "Application Diagnostics";
	public static final String LT_IPROCUREMENT = "iProcurement";
	public static final String SHOP = "ICXPOR_SHOP";
	public static final String REQUISITION = "ICXPOR_REQSTATUS";
	public static final String POST_AWARD_REQUESTS = "ICX_PAR_TAB";
	public static final String RECEIVING = "ICXPOR_RECEIVING_HOME";
	public static final String CONTRACTORS = "ICX_POR_CONTRACTOR";
	public static final String FEEDBACK = "ICX_POR_FEEDBACK";
	public static final String SHOP_STORES = "";
	public static final String SHOP_SHOPPING_LIST = "";
	public static final String SHOP_NON_CATALOG_REQUEST = "ICXPOR_NONCATALOG";
	public static final String SHOP_CONTRACTOR_REQUEST = "";
	public static final String NCR_ITEM_DESCRIPTION = "ItemDescription";
	public static final String NCR_CATEGORY = "Category";
	public static final String NCR_QUANTITY = "Quantity";
	public static final String NCR_UNIT_OF_MEASURE = "UnitOfMeasureTl";
	public static final String NCR_UNIT_PRICE = "UnitPrice";
	public static final String NCR_CURRENCY= "Currency";
	public static final String NCR_ADD_TO_CART= "AddToCart";
	public static final String NCR_SHOPPING_CART = "";
	public static  final String NCR_VIEW_CART_AND_CHECKOUT = "PopupCheckout";
	public static final String NCR_ITEM_TYPE = "ItemType";
	
	//Shopping cart modal fields
	public static final String SHOPPING_CART_DESCRIPTION = "ReqDescription";
	public static final String SHOPPING_CART_JUSTIFICATION = "ReqJustification";
	public static final String SHOPPING_CART_NEED_BY_DATE = "NeedByDate";
	public static final String SHOPPING_CART_DELIVER_TO_LOCATION = "DeliverToLocation";
	public static final String SHOPPING_CART_CONTINUE_SHOPPING = "ShoppingPopupClose";
	public static final String SHOPPING_CART_SUBMIT = "ShoppingPopupSubmit";
	public static final String SHOPPING_CART_EDIT = "ShoppingPopupReview";
	public static final String SHOPPING_CART_SAVE ="ShoppingPopupSave";
	
	//Requisition Decision page Strings 
	 public static final String RP_APPROVE = "//*[@id=\"rowLayout\"]/td[2]/button";
	 public static final String CSS_REJECT = "button[title='Reject']";
	 public static final String CSS_APPROVE_AND_FORWARD = "button[title='Approve And Forward']";
	 public static final String ID_FORWARD = "Forward";
	 public static final String ID_REASSIGN = "NtfReassign";
	 public static final String ID_REQUEST_INORMATION = "NtfMoreInfo";
	
	 
	//String constants  for switch statements 
	 public static final String SW_APPROVE = "Approve";
	 public static final String SW_REJECT = "Reject";
	 public static final String SW_APPROVE_AND_FORWARD = "Approve and forward";
	 public static final String SW_FORWARD = "Forward";
	 public static final String SW_REASSIGN = "Re-Assign";
	 public static final String SW_REQUEST_INORMATION = "Request Information";
	 
	//Left menu strings
	public static final String ADVANCED_PLANNING_ADMINISTRATOR = "Advanced Planning Administrator";
	public static final String ALERT_MANAGER_VISION_ENTERPRISES = "Alert Manager, Vision Enterprises";
	public static final String APPLICATION_DEVELOPER = "Application Developer";
	public static final String APPLICATION_DIAGONOSTICS = "Application Diagnostics";
	public static final String APPROVALS_MANAGEMENT_ADMINISTRATOR = "Approvals Management Administrator";
	public static final String APPROVALS_MANAGEMENT_BUSINESS_ANALYST = "Approvals Management Business Analyst";
	public static final String ASSET_INQUIRY_VISION_OPERATIONS = "Asset Inquiry, Vision Operations (USA)";
	public static final String ASSET_TRACKING_SUPER_USER = "Asset Tracking Super User, Vision Operations";
	public static final String ASSETS_VISION_OPERATIONS = "Assets, Vision Operations (USA)";
	public static final String BILL_PRESENTMENT_SUPER_USER_VISION_OPERATIONS_USA = "Bill Presentment Super User, Vision Operations (USA)";
	public static final String BUSINESS_INTELLIGENCE_SYSTEM_VISION_OPERATIONS_USA = "Business Intelligence System, Vision Operations (USA)";
	public static final String CADVIEW_3D_ADMINISTRATION = "CADView-3D Administration";
	public static final String CADVIEW_3D_USER = "CADView-3D User";
	public static final String CASH_MANAGEMENT_SETUP = "Cash Management Setup";
	public static final String CASH_MANAGEMENT_VISION_OPERATIONS_USA = "Cash Management, Vision Operations (USA)";
	public static final String CASH_MANAGEMENT_VISION_PAYROLL_USA = "Cash Management, Vision Payroll (USA)";
	public static final String COLLECTIONS_ADMINISTRATOR = "Collections Administrator";
	public static final String COLLECTIONS_AGENT = "Collections Agent";
	public static final String COLLECTIONS_MANAGER = "Collections Manager";
	public static final String CONTRACTS_WORKBENCH_USER = "Contracts Workbench User";
	public static final String COST_MANAGEMENT_SLA_VISION_OPERATIONS = "Cost Management - SLA Vision Operations";
	public static final String CREDIT_MANAGEMENT_SUPER_USER = "Credit Management Super User";
	public static final String CREDIT_SCHEDULER = "Credit Scheduler";
	public static final String CRL_11I_PROJECTS = "CRL 11i Projects";
	public static final String CRM_RESOURCE_MANAGER_VISION_ENTERPRISES = "CRM Resource Manager, Vision Enterprises";
	public static final String CUSTOMER_SUPPORT_ASSET_MAINTENANCE = "Customer Support - Asset Maintenance";
	public static final String CUSTOMERS_ONLINE_SUPERUSER = "Customers Online Superuser";
	public static final String DAILY_COMMODITY_INTELLIGENCE = "Daily Commodity Intelligence";
	public static final String DAILY_CUSTOMER_SUPPORT_INTELLIGENCE_VISION_OPERATIONS = "Daily Customer Support Intelligence, Vision Operations";
	public static final String DAILY_FINANCIALS_INTELLIGENCE = "Daily Financials Intelligence";
	public static final String DAILY_HR_INTELLIGENCE = "Daily HR Intelligence";
	public static final String DAILY_INTERACTION_CENTER_INTELLIGENCE = "Daily Interaction Center Intelligence";
	public static final String DAILY_PAYABLES_INTELLIGENCE = "Daily Payables Intelligence";
	public static final String DAILY_PROCUREMENT_INTELLIGENCE = "Daily Procurement Intelligence";
	public static final String DAILY_PROCUREMENT_SPEND_INTELLIGENCE = "Daily Procurement Spend Intelligence";
	public static final String DAILY_SOURCING_INTELLIGENCE = "Daily Sourcing Intelligence";
	public static final String DBI_CUSTOM_PAGES_AND_REPORTS = "DBI Custom Pages and Reports";
	public static final String DBI_INCREMENTAL_REQUEST_SETS = "DBI Incremental Request Sets";
	public static final String DESKTOP_INTEGRATION = "Desktop Integration";
	public static final String DESKTOP_INTEGRATION_MANAGER = "Desktop Integration Manager";
	public static final String DGF_ADMINISTRATOR_PURCHASING = "DGF Administrator - Purchasing";
	public static final String ECOMMERCE_GATEWAY_VISION_ENTERPRISES = "e-Commerce Gateway, Vision Enterprises";
	public static final String EMPLOYEE_SELF_SERVICE = "Employee Self-Service";
	public static final String ENTERPRISE_ASSET_MANAGEMENT_VISION_OPERATIONS = "Enterprise Asset Management, Vision Operations";
	public static final String ENTERPRISE_INSTALL_BASE_VISION_OPERATIONS = "Enterprise Install Base, Vision Operations";
	public static final String ENTERPRISE_PLANNING_AND_BUDGETING_ANALYST = "Enterprise Planning and Budgeting Analyst";
	public static final String ERES_ADMINISTRATOR = "ERES Administrator";
	public static final String FACILITY_OPERATIONS_VISION_OPERATIONS_USA = "Facility Operations, Vision Operations (USA)";
	public static final String FINANCIAL_INFORMATION_SYSTEM = "Financial Information System";
	public static final String FUNCTIONAL_ADMINISTRATOR = "Functional Administrator";
	public static final String GENERAL_LEDGER_IFRS_REPORTING_VISION_OPS = "General Ledger, IFRS Reporting Vision Ops";
	public static final String GENERAL_LEDGER_VISION_OPERATIONS_USA = "General Ledger, Vision Operations (USA)";
	public static final String HUMAN_RESOURCES_VISION_ENTERPRISES = "Human Resources, Vision Enterprises";
	public static final String IEXPENSES = "iExpenses";
	public static final String INSTALL_BASE_ADMININISTRATOR = "Install Base Admininistrator";
	public static final String INSTALL_BASE_USER = "Install Base User";
	public static final String INTERACTION_HISTORY_JSP_ADMIN = "Interaction History JSP Admin";
	public static final String INTERCOMPANY_SUPER_USER_VISION_OPERATIONS_USA = "Intercompany Super User, Vision Operations (USA)";
	public static final String INTERNET_EXPENSES_AUDITOR_VISION_OPERATIONS = "Internet Expenses Auditor, Vision Operations";
	public static final String INVENTORY_VISION_OPERATIONS_USA = "Inventory, Vision Operations (USA)";
	public static final String IPROCUREMENT = "iProcurement";
	public static final String IPROCUREMENT_CATALOG_ADMINISTRATION = "iProcurement Catalog Administration";
	public static final String IRECEIVABLES_INTERNAL_VISION_OPERATIONS_USA = "iReceivables Internal, Vision Operations (USA)";
	public static final String IRECEIVABLES_SETUP = "iReceivables Setup";
	public static final String IRECRUITMENT_EMPLOYEE_CANDIDATE = "iRecruitment Employee Candidate";
	public static final String ISUPPLIER_PORTAL_INTERNAL_VIEW  = "iSupplier Portal Internal View";
	public static final String ISUPPORT_SELF_SERVICE_HELPDESK = "iSupport Self-Service Helpdesk";
	public static final String ISURVEY_USER = "iSurvey User";
	public static final String LOAN_ADMINISTRATION_VISION_OPERATIONS_USA = "Loan Administration, Vision Operations (USA)";
	public static final String LOAN_AGENT_VISION_OPERATIONS_USA = "Loan Agent, Vision Operations (USA)";
	public static final String MAINTENANCE_SUPER_USER_FACILITIES = "Maintenance Super User, Facilities";
	public static final String MAINTENANCE_SUPER_USER_VISION_OPERATIONS = "Maintenance Super User, Vision Operations";
	public static final String MAINTENANCE_USER_WORKBENCH_VISION_OPERATIONS = "Maintenance User Workbench, Vision Operations";
	public static final String MANAGER_SELF_SERVICE = "Manager Self-Service";
	public static final String OBI_APPLICATIONS = "OBI Applications";
	public static final String OPERATIONS_INTELLIGENCE = "Operations Intelligence";
	public static final String ORACLE_PAYMENTS_PAYMENT_ADMINISTRATOR = "Oracle Payments Payment Administrator";
	public static final String ORACLE_PRICING_MANAGER_GLOBAL = "Oracle Pricing Manager, Global";
	public static final String ORACLE_PRICING_MANAGER_GLOBAL_PURCHASING = "Oracle Pricing Manager, Global (Purchasing)";
	public static final String ORACLE_TRADE_MANAGEMENT_USER = "Oracle Trade Management User";
	public static final String ORDER_MANAGEMENT_SUPER_USER_VISION_OPERATIONS_USA = "Order Management Super User, Vision Operations (USA)";
	public static final String OTL_OPERATIONS = "OTL, Operations";
	public static final String PAYABLES_VISION_OPERATIONS_USA = "Payables, Vision Operations (USA)";
	public static final String PAYMENTS_SETUP_ADMINISTRATOR = "Payments Setup Administrator";
	public static final String PERFORMANCE_MANAGEMENT_DESIGNER = "Performance Management Designer";
	public static final String PERFORMANCE_MANAGEMENT_USER = "Performance Management User";
	public static final String PREFERENCES_SSWA = "Preferences SSWA";
	public static final String PROFITABILITY_MANAGER_WITH_ACTIVITY_BASED_MANAGEMENT_ADMINISTRATOR = "Profitability Manager with Activity-Based Management - Administrator";
	public static final String PROJECT_CONTRACTS_VISION_OPERATIONS_USA = "Project Contracts, Vision Operations (USA)";
	public static final String PROJECT_INTELLIGENCE_SU_VISION_OPERATIONS_USA = "Project Intelligence SU, Vision Operations (USA)";
	public static final String PROJECT_MANAGER_VISION_OPERATIONS_USA = "Project Manager, Vision Operations (USA)";
	public static final String PROJECTS_CRL_VISION_OPERATIONS_USA = "Projects CRL, Vision Operations (USA)";
	public static final String PROJECTS_SU_VISION_OPERATIONS_USA = "Projects SU, Vision Operations (USA)";
	public static final String PROJECTS_VISION_OPERATIONS_USA = "Projects, Vision Operations (USA)";
	public static final String PROPERTY_MANAGER_VISION_OPERATIONS_USA = "Property Manager, Vision Operations (USA)";
	public static final String PURCHASING_VISION_OPERATIONS_USA = "Purchasing, Vision Operations (USA)";
	public static final String RECEIVABLES_VISION_OPERATIONS_USA = "Receivables, Vision Operations (USA)";
	public static final String REPORT_EXCHANGE_DESIGNER = "Report eXchange Designer";
	public static final String REPORT_MANAGER_SUPERUSER = "Report Manager SuperUser";
	public static final String REVENUE_MANAGEMENT_SUPER_USER_VISION_OPERATIONS_USA = "Revenue Management Super User, Vision Operations (USA)";
	public static final String RISK_MANAGEMENT_VISION_OPERATIONS_USA = "Risk Management, Vision Operations (USA)";
	public static final String SALES_ADMINISTRATOR = "Sales Administrator";
	public static final String SALES_USER = "Sales User";
	public static final String SCRIPTING_ADMINISTRATOR = "Scripting Administrator";
	public static final String SELF_SERVICE_WEB_APPLICATIONS_MANAGER_VISION_ENTERPRISES = "Self Service Web Applications Manager, Vision Enterprises";
	public static final String SERVICE_DESK_ANALYST = "Service Desk Analyst";
	public static final String SFM_SYSTEM_ADMINISTRATOR = "SFM System Administrator";
	public static final String SITE_MANAGEMENT_ADMINISTRATOR = "Site Management Administrator";
	public static final String SITE_MANAGEMENT_USER = "Site Management User";
	public static final String SOURCING_EMD_ADMINISTRATION = "Sourcing EMD Administration";
	public static final String SOURCING_SUPER_USER = "Sourcing Super User";
	public static final String SUPPLIER_DATA_LIBRARIAN_SUPER_USER = "Supplier Data Librarian Super User";
	public static final String SUPPLIER_MANAGEMENT_ADMINISTRATOR = "Supplier Management Administrator";
	public static final String SUPPLIER_MANAGER = "Supplier Manager";
	public static final String SURVEY_ADMINISTRATOR = "Survey Administrator";
	public static final String SYSTEM_ADMINISTRATION = "System Administration";
	public static final String SYSTEM_ADMINISTRATOR = "System Administrator";
	public static final String TAX_MANAGER_VISION_OPERATIONS  = "Tax Manager, Vision Operations";
	public static final String TRADING_COMMUNITY_MANAGER = "Trading Community ";
	public static final String TREASURY_CUSTOM_WORKBOOKS = "Treasury Custom Workbooks";
	public static final String TREASURY_CASH_AND_RISK_MANAGEMENT_SUPERUSER = "Treasury, Cash and Risk Management Superuser";
	public static final String TREASURY_VISION_OPERATIONS_USA = "Treasury, Vision Operations (USA)";
	public static final String UNIVERSAL_WORK_QUEUE_WORK_PROVIDER_SITE_LEVEL_ADMINISTRATION = "Universal Work Queue - Work Provider Site-Level Administration";
	public static final String US_LEARNER_MANAGER = "US Learner Manager";
	public static final String US_LEARNER_SELF_SERVICE = "US Learner Self-Service";
	public static final String US_LEARNING_MANAGEMENT_ADMINISTRATOR = "US Learning Management Administrator";
	public static final String WORKFLOW = "Workflow";
	public static final String WORKFLOW_ADMINISTRATOR_WEB_APPLICATIONS = "Workflow Administrator Web Applications";
	public static final String WORKFLOW_USER_VISION_ENTERPRISES = "Workflow User, Vision Enterprises";
	public static final String XML_GATEWAY = "XML Gateway";
	public static final String XML_PUBLISHER_ADMINISTRATOR = "XML Publisher Administrator";
//	public static final String NCR_ITEM_DESCRIPTION = null;
	public static final String NCR_CLEAR_ALL = "ClearAll";
	public static final String SHOPPING_CART_DELETE = null;
	
	
	/*public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	public static final String = "";
	*
	*/
	
}
